services:
  product-service:
    build: ./productservice
    ports:
      - "8082:8082"
  order-service:
    build: ./orderservice
    ports:
      - "8081:8081"
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      -  postgresql-volume:/var/lib/postgresql/data
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
  discovery-server:
    build: ./discoveryserver
    ports:
      - "8761:8761"
  gateway-server:
    build: ./gatewayserver
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8888/eureka/
volumes:
  postgresql-volume: #hangi image için volume oluşturulacaksa onun adı yazılır
    name: postgresql-volume1 #oluşturulacak volume'ün adı
